name: Build A15 GS201 Kernel

on:
  push:  # Trigger the workflow when changes are pushed to the repository
    branches:
      - main  # Replace with the branch name you want to monitor
      - development  # Add additional branches if needed
  pull_request:  # Trigger the workflow for pull requests
    branches:
      - main
  schedule:  # Trigger the workflow on a schedule (e.g., daily at midnight UTC)
    - cron: '0 0 * * *'

jobs:
  build-kernel-a15-gs201-kernelsu-susfs:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Installing dependencies
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Set CONFIG Environment Variable
        run: |
          CONFIG="android_kernel_google_gs201"
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "15.0.0-sultan-gs201"
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-android13-5.10"
          git clone https://github.com/TheWildJames/kernel_patches.git
          git clone https://github.com/kerneltoast/android_kernel_google_gs201

      # Add your remaining steps here as per the original workflow...

      - name: Build the Kernel
        run: |
          cd "$CONFIG"
          make gs201_defconfig -j$(nproc --all)
          make -j$(nproc --all)

      - name: Copy Images
        run: |
          cd "$CONFIG"
          cp ./out/arch/arm64/boot/Image.lz4 ../AnyKernel3/Image.lz4
          cat ./out/arch/arm64/boot/dts/google/*.dtb > ../AnyKernel3/dtb
          cp ./out/arch/arm64/boot/dts/google/dtbo.img ../AnyKernel3/dtbo.img

      - name: Create ZIP Files for Different Formats
        run: |
          cd ./AnyKernel3
          ZIP_NAME="A15_Sultan_KernelSU_SUSFS_GS201.zip"
          zip -r "../$ZIP_NAME" ./*

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-artifacts
          path: A15_Sultan_KernelSU_SUSFS_GS201.zip

          name: kernel-gs201
          path: |
            *.zip
