name: Build A15 GS201 Kernel

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-kernel-a15-gs201-kernelsu-susfs:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Installing dependencies
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu abootimg mkbootimg

      - name: Set CONFIG Environment Variable
        run: |
          CONFIG="android_kernel_google_gs201"
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "15.0.0-sultan-gs201"
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-android13-5.10"
          git clone https://github.com/TheWildJames/kernel_patches.git
          git clone https://github.com/kerneltoast/android_kernel_google_gs201

      # Add your patching steps here...

      - name: Build the Kernel
        run: |
          cd "$CONFIG"
          make gs201_defconfig -j$(nproc --all)
          make -j$(nproc --all)

      - name: Copy Images
        run: |
          cd "$CONFIG"
          cp ./out/arch/arm64/boot/Image.lz4 ../AnyKernel3/Image.lz4
          cat ./out/arch/arm64/boot/dts/google/*.dtb > ../AnyKernel3/dtb
          cp ./out/arch/arm64/boot/dts/google/dtbo.img ../AnyKernel3/dtbo.img

      - name: Create init_boot.img
        run: |
          echo "Creating init_boot.img..."
          mkbootimg --kernel ../AnyKernel3/Image.lz4 \
                    --ramdisk ../AnyKernel3/dtbo.img \
                    --dtb ../AnyKernel3/dtb \
                    --cmdline "console=ttyS0,115200n8 earlyprintk" \
                    --base 0x80000000 \
                    --pagesize 4096 \
                    --os_version 13.0.0 \
                    --os_patch_level 2023-01-01 \
                    --output ./init_boot.img

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: init_boot.img
          path: ./init_boot.img
